"""
============================================================
Learned Rules — Auto-Generated by RuleLearningAgent
============================================================
These rules were discovered by the LLM fallback engine and
validated against MCP documentation. They follow the same
interface as deterministic rules in CodeAnalysisAgent:

    def rule_name(lines, code, sample) -> Optional[Tuple[int, str, float]]
        Returns (line_number, explanation, confidence) or None

DO NOT EDIT MANUALLY unless you understand the implications.
============================================================
"""

import re
from typing import List, Optional, Tuple

# Rule registry — maps rule_name to function
LEARNED_RULES = {}


def register_rule(name):
    """Decorator to register a learned rule."""
    def decorator(fn):
        LEARNED_RULES[name] = fn
        return fn
    return decorator


# ── Learned Rules Below ────────────────────────────────────


# ── Rule: vforce_numeric_argument ──────────────────────────────────────
# Hash: 2cf8189a0d631653
# Learned: 2026-02-10 13:18:18
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that calls to vForce provide a plain numeric value (int, float, double) without embedded unit strings.
@register_rule("vforce_numeric_argument")
def _check_vforce_numeric_argument(lines, code, sample):
    """
    Ensures that calls to vForce provide a plain numeric value (int, float, double) without embedded unit strings.
    Detection: vForce\s*\(\s*[^0-9\-+\.].*\)
    """
    try:
        pattern = re.compile(r"""vForce\s*\(\s*[^0-9\-+\.].*\)""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_type — Ensures that calls to vForce provide a plain numeric value (int, float, double) without embedded unit strings."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """vForce\s*\(\s*[^0-9\-+\.].*\)""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_type — Ensures that calls to vForce provide a plain numeric value (int, float, double) without embedded unit strings."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    return None


# ── Rule: invalid_addwaveform_on_waveform ──────────────────────────────────────
# Hash: ec71cd49fc211f31
# Learned: 2026-02-10 13:18:20
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Detect calls to addWaveform directly after a waveform() call, which indicates misuse of the API because addWaveform should be called on a collection or pin, not on a single Waveform object.
@register_rule("invalid_addwaveform_on_waveform")
def _check_invalid_addwaveform_on_waveform(lines, code, sample):
    """
    Detect calls to addWaveform directly after a waveform() call, which indicates misuse of the API because addWaveform should be called on a collection or pin, not on a single Waveform object.
    Detection: \.waveform\s*\([^\)]*\)\s*\.addWaveform\s*\(
    """
    try:
        pattern = re.compile(r"""\.waveform\s*\([^\)]*\)\s*\.addWaveform\s*\(""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: invalid_api_call — Detect calls to addWaveform directly after a waveform() call, which indicates misuse of the API because addWaveform should be called on a collection or pin, not on a single Waveform object."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.92)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """\.waveform\s*\([^\)]*\)\s*\.addWaveform\s*\(""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: invalid_api_call — Detect calls to addWaveform directly after a waveform() call, which indicates misuse of the API because addWaveform should be called on a collection or pin, not on a single Waveform object."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.92)
    return None


# ── Rule: smartvec_readmode_invalid_enum ──────────────────────────────────────
# Hash: 611a17844b335d5c
# Learned: 2026-02-10 13:18:21
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that calls to SmartVec::readMode use a value from the SmartVec::ReadMode enumeration rather than an unrelated enum.
@register_rule("smartvec_readmode_invalid_enum")
def _check_smartvec_readmode_invalid_enum(lines, code, sample):
    """
    Ensures that calls to SmartVec::readMode use a value from the SmartVec::ReadMode enumeration rather than an unrelated enum.
    Detection: Detect calls to readMode\s*\(\s*[^:]+::[^)]+\s*\) where the argument's type is not SmartVec::ReadMode
    """
    try:
        pattern = re.compile(r"""Detect calls to readMode\s*\(\s*[^:]+::[^)]+\s*\) where the argument's type is not SmartVec::ReadMode""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument — Ensures that calls to SmartVec::readMode use a value from the SmartVec::ReadMode enumeration rather than an unrelated enum."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.88)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """Detect calls to readMode\s*\(\s*[^:]+::[^)]+\s*\) where the argument's type is not SmartVec::ReadMode""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument — Ensures that calls to SmartVec::readMode use a value from the SmartVec::ReadMode enumeration rather than an unrelated enum."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.88)
    return None


# ── Rule: vforce_numeric_argument ──────────────────────────────────────
# Hash: 928d8344c28b5c6d
# Learned: 2026-02-10 13:18:25
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that the vForce API is called with a pure numeric argument (float/double) without embedded unit strings.
@register_rule("vforce_numeric_argument")
def _check_vforce_numeric_argument(lines, code, sample):
    """
    Ensures that the vForce API is called with a pure numeric argument (float/double) without embedded unit strings.
    Detection: vForce\s*\(\s*[^\d]*\d+\s+[A-Za-z]+\s*\)
    """
    try:
        pattern = re.compile(r"""vForce\s*\(\s*[^\d]*\d+\s+[A-Za-z]+\s*\)""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_type — Ensures that the vForce API is called with a pure numeric argument (float/double) without embedded unit strings."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """vForce\s*\(\s*[^\d]*\d+\s+[A-Za-z]+\s*\)""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_type — Ensures that the vForce API is called with a pure numeric argument (float/double) without embedded unit strings."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    return None


# ── Rule: rdi_vforce_argument_must_be_numeric ──────────────────────────────────────
# Hash: 5f5f31ede6472ca8
# Learned: 2026-02-10 13:24:20
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that calls to rdi.dc().pin(...).vForce(...) provide a plain numeric value (int, float, double) without unit suffixes or invalid tokens.
@register_rule("rdi_vforce_argument_must_be_numeric")
def _check_rdi_vforce_argument_must_be_numeric(lines, code, sample):
    """
    Ensures that calls to rdi.dc().pin(...).vForce(...) provide a plain numeric value (int, float, double) without unit suffixes or invalid tokens.
    Detection: vForce\s*\(\s*[^0-9\-+\.\)]+\s*\)
    """
    try:
        pattern = re.compile(r"""vForce\s*\(\s*[^0-9\-+\.\)]+\s*\)""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_literal — Ensures that calls to rdi.dc().pin(...).vForce(...) provide a plain numeric value (int, float, double) without unit suffixes or invalid tokens."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """vForce\s*\(\s*[^0-9\-+\.\)]+\s*\)""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_literal — Ensures that calls to rdi.dc().pin(...).vForce(...) provide a plain numeric value (int, float, double) without unit suffixes or invalid tokens."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    return None


# ── Rule: invalid_method_sequence_after_waveform ──────────────────────────────────────
# Hash: 3acbb32f6654ea37
# Learned: 2026-02-10 13:24:26
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Detect calls to collection‑modifying methods (e.g., addWaveform) directly after a waveform() call, which returns a Waveform object that does not support those methods.
@register_rule("invalid_method_sequence_after_waveform")
def _check_invalid_method_sequence_after_waveform(lines, code, sample):
    """
    Detect calls to collection‑modifying methods (e.g., addWaveform) directly after a waveform() call, which returns a Waveform object that does not support those methods.
    Detection: \.waveform\([^)]*\)\.addWaveform\(
    """
    try:
        pattern = re.compile(r"""\.waveform\([^)]*\)\.addWaveform\(""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: invalid_api_call — Detect calls to collection‑modifying methods (e.g., addWaveform) directly after a waveform() call, which returns a Waveform object that does not support those methods."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.94)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """\.waveform\([^)]*\)\.addWaveform\(""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: invalid_api_call — Detect calls to collection‑modifying methods (e.g., addWaveform) directly after a waveform() call, which returns a Waveform object that does not support those methods."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.94)
    return None


# ── Rule: rdi_vforce_numeric_argument ──────────────────────────────────────
# Hash: f0357e56217d5670
# Learned: 2026-02-10 13:24:29
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that the argument passed to rdi.dc().pin(...).vForce(...) is a numeric value or a defined voltage constant, not a string or malformed literal.
@register_rule("rdi_vforce_numeric_argument")
def _check_rdi_vforce_numeric_argument(lines, code, sample):
    """
    Ensures that the argument passed to rdi.dc().pin(...).vForce(...) is a numeric value or a defined voltage constant, not a string or malformed literal.
    Detection: vForce\s*\(\s*[^0-9\-\.]+\s*\)
    """
    try:
        pattern = re.compile(r"""vForce\s*\(\s*[^0-9\-\.]+\s*\)""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_type — Ensures that the argument passed to rdi.dc().pin(...).vForce(...) is a numeric value or a defined voltage constant, not a string or malformed literal."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """vForce\s*\(\s*[^0-9\-\.]+\s*\)""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_type — Ensures that the argument passed to rdi.dc().pin(...).vForce(...) is a numeric value or a defined voltage constant, not a string or malformed literal."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    return None


# ── Rule: missing_execute ──────────────────────────────────────
# Hash: 523dd05d00a41a9e
# Learned: 2026-02-10 13:55:30
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that any RDI command chain (e.g., dc, ac, vec) is concluded with a .execute() call before ending the lifecycle.
@register_rule("missing_execute")
def _check_missing_execute(lines, code, sample):
    """
    Ensures that any RDI command chain (e.g., dc, ac, vec) is concluded with a .execute() call before ending the lifecycle.
    Detection: rdi\.[a-zA-Z]+\([^)]*\)(?!.*\.execute\(\))
    """
    try:
        pattern = re.compile(r"""rdi\.[a-zA-Z]+\([^)]*\)(?!.*\.execute\(\))""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: missing_execute — Ensures that any RDI command chain (e.g., dc, ac, vec) is concluded with a .execute() call before ending the lifecycle."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """rdi\.[a-zA-Z]+\([^)]*\)(?!.*\.execute\(\))""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: missing_execute — Ensures that any RDI command chain (e.g., dc, ac, vec) is concluded with a .execute() call before ending the lifecycle."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    return None


# ── Rule: run_time_val_array_not_allowed ──────────────────────────────────────
# Hash: 36e36fa0d27d89cd
# Learned: 2026-02-10 13:55:32
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that rdi.runTimeVal is called only with scalar numeric arguments, not with array or container types.
@register_rule("run_time_val_array_not_allowed")
def _check_run_time_val_array_not_allowed(lines, code, sample):
    """
    Ensures that rdi.runTimeVal is called only with scalar numeric arguments, not with array or container types.
    Detection: rdi\.runTimeVal\s*\(\s*\"[^\"]+\"\s*,\s*[^\)]+\)\s*;\s*// flag if second argument is of type ARRAY_ or std::vector
    """
    try:
        pattern = re.compile(r"""rdi\.runTimeVal\s*\(\s*\"[^\"]+\"\s*,\s*[^\)]+\)\s*;\s*// flag if second argument is of type ARRAY_ or std::vector""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_type — Ensures that rdi.runTimeVal is called only with scalar numeric arguments, not with array or container types."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.94)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """rdi\.runTimeVal\s*\(\s*\"[^\"]+\"\s*,\s*[^\)]+\)\s*;\s*// flag if second argument is of type ARRAY_ or std::vector""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: invalid_argument_type — Ensures that rdi.runTimeVal is called only with scalar numeric arguments, not with array or container types."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.94)
    return None


# ── Rule: dc_chain_requires_execute ──────────────────────────────────────
# Hash: 370e692e808e006e
# Learned: 2026-02-10 13:55:34
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: All RDI DC configuration chains must end with a call to .execute() to commit the settings.
@register_rule("dc_chain_requires_execute")
def _check_dc_chain_requires_execute(lines, code, sample):
    """
    All RDI DC configuration chains must end with a call to .execute() to commit the settings.
    Detection: rdi\.dc\(\).*\.(?!execute\(\)).*$
    """
    try:
        pattern = re.compile(r"""rdi\.dc\(\).*\.(?!execute\(\)).*$""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: missing_execute — All RDI DC configuration chains must end with a call to .execute() to commit the settings."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """rdi\.dc\(\).*\.(?!execute\(\)).*$""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: missing_execute — All RDI DC configuration chains must end with a call to .execute() to commit the settings."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    return None


# ── Rule: missing_execute ──────────────────────────────────────
# Hash: 0ec0778d898a08fd
# Learned: 2026-02-10 13:55:36
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that any RDI/SmartRDI configuration chain (e.g., dc(), smartVec(), etc.) ends with an .execute() call before the statement terminates.
@register_rule("missing_execute")
def _check_missing_execute(lines, code, sample):
    """
    Ensures that any RDI/SmartRDI configuration chain (e.g., dc(), smartVec(), etc.) ends with an .execute() call before the statement terminates.
    Detection: rdi\.[a-zA-Z]+\([^\)]*\)(?:\.[a-zA-Z_]+\([^\)]*\))*\s*;(?!.*\.execute\s*\()
    """
    try:
        pattern = re.compile(r"""rdi\.[a-zA-Z]+\([^\)]*\)(?:\.[a-zA-Z_]+\([^\)]*\))*\s*;(?!.*\.execute\s*\()""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: missing_execute — Ensures that any RDI/SmartRDI configuration chain (e.g., dc(), smartVec(), etc.) ends with an .execute() call before the statement terminates."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.94)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """rdi\.[a-zA-Z]+\([^\)]*\)(?:\.[a-zA-Z_]+\([^\)]*\))*\s*;(?!.*\.execute\s*\()""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: missing_execute — Ensures that any RDI/SmartRDI configuration chain (e.g., dc(), smartVec(), etc.) ends with an .execute() call before the statement terminates."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.94)
    return None


# ── Rule: missing_lifecycle_end ──────────────────────────────────────
# Hash: e0f9f51b26c99ba1
# Learned: 2026-02-10 13:55:38
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that every RDI_BEGIN() is paired with a corresponding RDI_END() within the same scope.
@register_rule("missing_lifecycle_end")
def _check_missing_lifecycle_end(lines, code, sample):
    """
    Ensures that every RDI_BEGIN() is paired with a corresponding RDI_END() within the same scope.
    Detection: Detect a call to RDI_BEGIN() without a subsequent RDI_END() before the end of the function or block.
    """
    try:
        pattern = re.compile(r"""Detect a call to RDI_BEGIN() without a subsequent RDI_END() before the end of the function or block.""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: missing_lifecycle_end — Ensures that every RDI_BEGIN() is paired with a corresponding RDI_END() within the same scope."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """Detect a call to RDI_BEGIN() without a subsequent RDI_END() before the end of the function or block.""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: missing_lifecycle_end — Ensures that every RDI_BEGIN() is paired with a corresponding RDI_END() within the same scope."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    return None


# ── Rule: consistent_identifier_usage ──────────────────────────────────────
# Hash: 4e622b097e8de2ce
# Learned: 2026-02-10 13:55:41
# Severity: HIGH
# Source: LLM (Groq OSS-120B) + MCP Validation
# Description: Ensures that the identifier string used in measurement setup (e.g., func, pin, digCap) matches the identifier used in subsequent retrieval calls (e.g., id, get...).
@register_rule("consistent_identifier_usage")
def _check_consistent_identifier_usage(lines, code, sample):
    """
    Ensures that the identifier string used in measurement setup (e.g., func, pin, digCap) matches the identifier used in subsequent retrieval calls (e.g., id, get...).
    Detection: Look for a setup chain containing .func\(\"([^\"]+)\"\).* followed by a later call .id\(\"(?!\1)[^\"]+\"\)
    """
    try:
        pattern = re.compile(r"""Look for a setup chain containing .func\(\"([^\"]+)\"\).* followed by a later call .id\(\"(?!\1)[^\"]+\"\)""", re.IGNORECASE)
        for line_obj in lines:
            if pattern.search(line_obj.stripped):
                explanation = (
                    f"Line {line_obj.line_number}: variable_mismatch — Ensures that the identifier string used in measurement setup (e.g., func, pin, digCap) matches the identifier used in subsequent retrieval calls (e.g., id, get...)."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    except re.error:
        # If the pattern is not valid regex, use substring matching
        search_term = """Look for a setup chain containing .func\(\"([^\"]+)\"\).* followed by a later call .id\(\"(?!\1)[^\"]+\"\)""".lower()
        for line_obj in lines:
            if search_term in line_obj.stripped.lower():
                explanation = (
                    f"Line {line_obj.line_number}: variable_mismatch — Ensures that the identifier string used in measurement setup (e.g., func, pin, digCap) matches the identifier used in subsequent retrieval calls (e.g., id, get...)."
                    f" |"
                    f" | Impact: Potential API misuse detected."
                )
                return (line_obj.line_number, explanation, 0.96)
    return None


# Hash: 6b29c28259ebff46
@register_rule("rdi_func_burst_chain")
def _chk_rdi_func_burst_chain(lines, code, sample):
    """Detects illegal chaining of burst() calls after a func().burst(...) invocation."""
    import re
    try:
        pat = re.compile(r"""port\s*\(.*\)\.func\(\)\.burst\([^\)]*\)\.burst\s*\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_burst_chaining - Detects illegal chaining of burst() calls after a func().burst(...) invocation. |", 0.96)
    except:
        sm = """port\s*\(.*\)\.func\(\)\.burst\([^\)]*\)\.burst\s*\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_burst_chaining - Detects illegal chaining of burst() calls after a func().burst(...) invocation. |", 0.96)
    return None

# Hash: d9de0d7ce9efd915
@register_rule("rdi_method_chain_validity")
def _chk_rdi_method_chain_validity(lines, code, sample):
    """Ensure that every identifier in an RDI method chain corresponds to a defined RDI API function and is invoked with correct syntax (including parentheses for functions)."""
    import re
    try:
        pat = re.compile(r"""rdi\.[a-zA-Z]+\([^)]*\)(\.[a-zA-Z_][a-zA-Z0-9_]*;|\.[a-zA-Z_][a-zA-Z0-9_]*\([^)]*\);)""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - Ensure that every identifier in an RDI method chain corresponds to a defined RDI API function and is invoked with correct syntax (including parentheses for functions). |", 0.96)
    except:
        sm = """rdi\.[a-zA-Z]+\([^)]*\)(\.[a-zA-Z_][a-zA-Z0-9_]*;|\.[a-zA-Z_][a-zA-Z0-9_]*\([^)]*\);)""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - Ensure that every identifier in an RDI method chain corresponds to a defined RDI API function and is invoked with correct syntax (including parentheses for functions). |", 0.96)
    return None

# Hash: 4602c3056789595b
@register_rule("rdi_burst_sequence")
def _chk_rdi_burst_sequence(lines, code, sample):
    """When using func() with multi‑port bursts, the burst() method must be called exactly once; chaining another burst() after it is invalid."""
    import re
    try:
        pat = re.compile(r"""func\(\)\.burst\([^\)]*\)\.burst\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_burst_sequence - When using func() with multi‑port bursts, the burst() method must be called exactly once; chaining another burst() after it is invalid. |", 0.96)
    except:
        sm = """func\(\)\.burst\([^\)]*\)\.burst\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_burst_sequence - When using func() with multi‑port bursts, the burst() method must be called exactly once; chaining another burst() after it is invalid. |", 0.96)
    return None

# Hash: 3110f00a30c2706b
@register_rule("rdi_method_call_syntax")
def _chk_rdi_method_call_syntax(lines, code, sample):
    """All RDI fluent‑interface methods must be invoked with parentheses; missing parentheses indicate an invalid method call."""
    import re
    try:
        pat = re.compile(r"""rdi\.[a-zA-Z0-9_]+\([^)]*\)(\.[a-zA-Z0-9_]+)(?!\()""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - All RDI fluent‑interface methods must be invoked with parentheses; missing parentheses indicate an invalid method call. |", 0.96)
    except:
        sm = """rdi\.[a-zA-Z0-9_]+\([^)]*\)(\.[a-zA-Z0-9_]+)(?!\()""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - All RDI fluent‑interface methods must be invoked with parentheses; missing parentheses indicate an invalid method call. |", 0.96)
    return None

# Hash: 0550c1c84a52fa4c
@register_rule("no_double_burst_after_func")
def _chk_no_double_burst_after_func(lines, code, sample):
    """When using rdi.port(...).func(), only one .burst(label) call is allowed. A subsequent .burst() without a new .func() constitutes misuse."""
    import re
    try:
        pat = re.compile(r"""port\s*\(.*\)\.func\(\)\..*\.burst\([^\)]*\)\.burst\s*\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: double_burst_call - When using rdi.port(...).func(), only one .burst(label) call is allowed. A subsequent .burst() without a new .func() constitutes misuse. |", 0.96)
    except:
        sm = """port\s*\(.*\)\.func\(\)\..*\.burst\([^\)]*\)\.burst\s*\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: double_burst_call - When using rdi.port(...).func(), only one .burst(label) call is allowed. A subsequent .burst() without a new .func() constitutes misuse. |", 0.96)
    return None

# Hash: 889eaff0f41c8b1f
@register_rule("rdi_invalidmethodchain")
def _chk_rdi_invalidmethodchain(lines, code, sample):
    """Detects usage of undefined or misspelled RDI API methods in fluent call chains."""
    import re
    try:
        pat = re.compile(r"""rdi\.[a-zA-Z]+\([^\)]*\)(\.[a-zA-Z]+\([^\)]*\))*\.[a-zA-Z]+(?!\()""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - Detects usage of undefined or misspelled RDI API methods in fluent call chains. |", 0.94)
    except:
        sm = """rdi\.[a-zA-Z]+\([^\)]*\)(\.[a-zA-Z]+\([^\)]*\))*\.[a-zA-Z]+(?!\()""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - Detects usage of undefined or misspelled RDI API methods in fluent call chains. |", 0.94)
    return None

# Hash: 062cf8cffab533cf
@register_rule("multiportburstsequence")
def _chk_multiportburstsequence(lines, code, sample):
    """When using func() with TA::MULTI_PORT, the API permits exactly one burst(name) call. Any additional .burst() call after that is a misuse."""
    import re
    try:
        pat = re.compile(r"""port\s*\(\s*TA::MULTI_PORT\s*\).*func\s*\(\s*\).*burst\s*\([^\)]*\)\s*\.\s*burst\s*\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_multiport_burst_sequence - When using func() with TA::MULTI_PORT, the API permits exactly one burst(name) call. Any additional .burst() call after that is a misuse. |", 0.96)
    except:
        sm = """port\s*\(\s*TA::MULTI_PORT\s*\).*func\s*\(\s*\).*burst\s*\([^\)]*\)\s*\.\s*burst\s*\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_multiport_burst_sequence - When using func() with TA::MULTI_PORT, the API permits exactly one burst(name) call. Any additional .burst() call after that is a misuse. |", 0.96)
    return None

# Hash: 2b693464ba3ae2f3
@register_rule("rdi_vectoridentifiermatch")
def _chk_rdi_vectoridentifiermatch(lines, code, sample):
    """Ensure that the identifier used in getVector matches a pin or capture name defined earlier in the RDI configuration."""
    import re
    try:
        pat = re.compile(r"""rdi\.id\([^\)]+\)\.getVector\(\"[^\"]+\"\)""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_vector_identifier - Ensure that the identifier used in getVector matches a pin or capture name defined earlier in the RDI configuration. |", 0.94)
    except:
        sm = """rdi\.id\([^\)]+\)\.getVector\(\"[^\"]+\"\)""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_vector_identifier - Ensure that the identifier used in getVector matches a pin or capture name defined earlier in the RDI configuration. |", 0.94)
    return None

# Hash: 1a58e0934ff82a69
@register_rule("funcburstsinglecall")
def _chk_funcburstsinglecall(lines, code, sample):
    """In func() mode, only one burst() call (with or without a name) may be issued. A subsequent burst() without parameters is an API misuse."""
    import re
    try:
        pat = re.compile(r"""func\(\)\.burst\([^\)]*\)\.burst\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_burst_sequence - In func() mode, only one burst() call (with or without a name) may be issued. A subsequent burst() without parameters is an API misuse. |", 0.97)
    except:
        sm = """func\(\)\.burst\([^\)]*\)\.burst\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_burst_sequence - In func() mode, only one burst() call (with or without a name) may be issued. A subsequent burst() without parameters is an API misuse. |", 0.97)
    return None

# Hash: c0b08760a17430a5
@register_rule("rdi_method_call_syntax")
def _chk_rdi_method_call_syntax(lines, code, sample):
    """All RDI method calls must include parentheses, even when they take no arguments."""
    import re
    try:
        pat = re.compile(r"""RDI_.*\.\w+;""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_method_parentheses - All RDI method calls must include parentheses, even when they take no arguments. |", 0.86)
    except:
        sm = """RDI_.*\.\w+;""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_method_parentheses - All RDI method calls must include parentheses, even when they take no arguments. |", 0.86)
    return None

# Hash: e45b2b9383c0897b
@register_rule("no_extra_burst_after_named_burst")
def _chk_no_extra_burst_after_named_burst(lines, code, sample):
    """When using func().burst(name) the returned object must not be followed by another .burst() call; only one burst invocation is allowed per func() chain."""
    import re
    try:
        pat = re.compile(r"""func\(\)\.burst\([^\)]*\)\.burst\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: duplicate_burst_call - When using func().burst(name) the returned object must not be followed by another .burst() call; only one burst invocation is allowed per func() chain. |", 0.96)
    except:
        sm = """func\(\)\.burst\([^\)]*\)\.burst\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: duplicate_burst_call - When using func().burst(name) the returned object must not be followed by another .burst() call; only one burst invocation is allowed per func() chain. |", 0.96)
    return None

# Hash: 8dc5cfe788087ac5
@register_rule("rdi_invalidmethodcall")
def _chk_rdi_invalidmethodcall(lines, code, sample):
    """Detect calls to non‑existent RDI API methods or misspelled method names."""
    import re
    try:
        pat = re.compile(r"""rdi\.digCap\([^)]*\)(?:\.[a-zA-Z_][a-zA-Z0-9_]*\([^)]*\))*\.[a-zA-Z_][a-zA-Z0-9_]*$""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - Detect calls to non‑existent RDI API methods or misspelled method names. |", 0.93)
    except:
        sm = """rdi\.digCap\([^)]*\)(?:\.[a-zA-Z_][a-zA-Z0-9_]*\([^)]*\))*\.[a-zA-Z_][a-zA-Z0-9_]*$""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - Detect calls to non‑existent RDI API methods or misspelled method names. |", 0.93)
    return None

# Hash: 3cbfc5e55cf658f3
@register_rule("no_multiple_burst_calls")
def _chk_no_multiple_burst_calls(lines, code, sample):
    """Prevent chaining multiple burst() calls on the same func() context; only one burst() (with optional name) should be invoked per func() invocation."""
    import re
    try:
        pat = re.compile(r"""func\(\)\.burst\([^\)]*\)\.burst\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_burst_chaining - Prevent chaining multiple burst() calls on the same func() context; only one burst() (with optional name) should be invoked per func() invocation. |", 0.96)
    except:
        sm = """func\(\)\.burst\([^\)]*\)\.burst\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_burst_chaining - Prevent chaining multiple burst() calls on the same func() context; only one burst() (with optional name) should be invoked per func() invocation. |", 0.96)
    return None

# Hash: 22740e948d2b3ee1
@register_rule("rdi_methodinvocationsyntax")
def _chk_rdi_methodinvocationsyntax(lines, code, sample):
    """All RDI API methods must be invoked with parentheses, even when they take no arguments."""
    import re
    try:
        pat = re.compile(r"""\.\w+\s*;""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_method_call_parentheses - All RDI API methods must be invoked with parentheses, even when they take no arguments. |", 0.96)
    except:
        sm = """\.\w+\s*;""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_method_call_parentheses - All RDI API methods must be invoked with parentheses, even when they take no arguments. |", 0.96)
    return None

# Hash: af8c50237e731b63
@register_rule("measurement_unit_validation")
def _chk_measurement_unit_validation(lines, code, sample):
    """Ensure that API functions receive arguments with the correct physical units; reject mismatched units such as voltage for current‑only parameters."""
    import re
    try:
        pat = re.compile(r"""vForce\s*\(\s*\d+\s+V\s*\)""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_measurement_unit - Ensure that API functions receive arguments with the correct physical units; reject mismatched units such as voltage for current‑only parameters. |", 0.96)
    except:
        sm = """vForce\s*\(\s*\d+\s+V\s*\)""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_measurement_unit - Ensure that API functions receive arguments with the correct physical units; reject mismatched units such as voltage for current‑only parameters. |", 0.96)
    return None

# Hash: 4cf4470498769d7f
@register_rule("rdi_use_correct_retrieval_method")
def _chk_rdi_use_correct_retrieval_method(lines, code, sample):
    """When accessing results of a digital capture, use the same API (digCap) that created the measurement; do not use id() which is for different object types."""
    import re
    try:
        pat = re.compile(r"""rdi\.id\s*\(.*\)\.getVector""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_measurement_retrieval - When accessing results of a digital capture, use the same API (digCap) that created the measurement; do not use id() which is for different object types. |", 0.94)
    except:
        sm = """rdi\.id\s*\(.*\)\.getVector""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_measurement_retrieval - When accessing results of a digital capture, use the same API (digCap) that created the measurement; do not use id() which is for different object types. |", 0.94)
    return None

# Hash: a5539a6691c6a662
@register_rule("rdi_beginend_mandatory")
def _chk_rdi_beginend_mandatory(lines, code, sample):
    """Ensure that every RDI measurement sequence is wrapped with RDI_BEGIN() before any configuration calls and RDI_END() after execution."""
    import re
    try:
        pat = re.compile(r"""rdi\..*\(.*\);(?!.*RDI_BEGIN).*?(?!.*RDI_END)""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin_end - Ensure that every RDI measurement sequence is wrapped with RDI_BEGIN() before any configuration calls and RDI_END() after execution. |", 0.96)
    except:
        sm = """rdi\..*\(.*\);(?!.*RDI_BEGIN).*?(?!.*RDI_END)""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin_end - Ensure that every RDI measurement sequence is wrapped with RDI_BEGIN() before any configuration calls and RDI_END() after execution. |", 0.96)
    return None

# Hash: ee0f988de5479c60
@register_rule("rdi_begin_end_enforcement")
def _chk_rdi_begin_end_enforcement(lines, code, sample):
    """Ensure all RDI API calls that configure or record measurements are enclosed within a matching RDI_BEGIN() and RDI_END() block."""
    import re
    try:
        pat = re.compile(r"""rdi\.[a-zA-Z0-9_]+\(\)\.[a-zA-Z0-9_]+\s*\([^;]*\);(?!.*RDI_BEGIN)""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin_end - Ensure all RDI API calls that configure or record measurements are enclosed within a matching RDI_BEGIN() and RDI_END() block. |", 0.87)
    except:
        sm = """rdi\.[a-zA-Z0-9_]+\(\)\.[a-zA-Z0-9_]+\s*\([^;]*\);(?!.*RDI_BEGIN)""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin_end - Ensure all RDI API calls that configure or record measurements are enclosed within a matching RDI_BEGIN() and RDI_END() block. |", 0.87)
    return None

# Hash: 3945024f343fe783
@register_rule("rdi_lifecycle_end")
def _chk_rdi_lifecycle_end(lines, code, sample):
    """Every RDI_BEGIN must be paired with a corresponding RDI_END before exiting the scope."""
    import re
    try:
        pat = re.compile(r"""RDI_BEGIN\s*\([^)]*\)(?![\s\S]*RDI_END)""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_rdi_end - Every RDI_BEGIN must be paired with a corresponding RDI_END before exiting the scope. |", 0.97)
    except:
        sm = """RDI_BEGIN\s*\([^)]*\)(?![\s\S]*RDI_END)""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_rdi_end - Every RDI_BEGIN must be paired with a corresponding RDI_END before exiting the scope. |", 0.97)
    return None

# Hash: f8eff6574f411235
@register_rule("rdi_measurementboundary")
def _chk_rdi_measurementboundary(lines, code, sample):
    """Ensure that any burst or functional measurement is enclosed between RDI_BEGIN() and RDI_END() calls."""
    import re
    try:
        pat = re.compile(r"""port\(.*\)\.func\(.*\)\.burstRunTime\(.*\)\.execute\(\);""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_measurement_boundary - Ensure that any burst or functional measurement is enclosed between RDI_BEGIN() and RDI_END() calls. |", 0.94)
    except:
        sm = """port\(.*\)\.func\(.*\)\.burstRunTime\(.*\)\.execute\(\);""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_measurement_boundary - Ensure that any burst or functional measurement is enclosed between RDI_BEGIN() and RDI_END() calls. |", 0.94)
    return None

# Hash: 4e4acf3c03fdf6c1
@register_rule("rdi_invalid_measurement_literal")
def _chk_rdi_invalid_measurement_literal(lines, code, sample):
    """Detects usage of malformed measurement literals (e.g., \"1 V\" with a space) in RDI API calls."""
    import re
    try:
        pat = re.compile(r"""vForce\s*\(\s*\d+\s+V\s*\)""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_measurement_literal - Detects usage of malformed measurement literals (e.g., \"1 V\" with a space) in RDI API calls. |", 0.96)
    except:
        sm = """vForce\s*\(\s*\d+\s+V\s*\)""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_measurement_literal - Detects usage of malformed measurement literals (e.g., \"1 V\" with a space) in RDI API calls. |", 0.96)
    return None

# Hash: dc15c0b53d62f5e4
@register_rule("rdi_type_mismatch")
def _chk_rdi_type_mismatch(lines, code, sample):
    """Ensure the variable type matches the measurement data type returned by getVector."""
    import re
    try:
        pat = re.compile(r"""rdi\.\w+\(.*\)\.getVector\(.*\)\s*=""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: type_mismatch_measurement - Ensure the variable type matches the measurement data type returned by getVector. |", 0.95)
    except:
        sm = """rdi\.\w+\(.*\)\.getVector\(.*\)\s*=""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: type_mismatch_measurement - Ensure the variable type matches the measurement data type returned by getVector. |", 0.95)
    return None

# Hash: b713b67c4f549785
@register_rule("rdi_begin_end_required")
def _chk_rdi_begin_end_required(lines, code, sample):
    """All RDI measurement specifications must be enclosed between RDI_BEGIN() and RDI_END() calls."""
    import re
    try:
        pat = re.compile(r"""rdi\..*\(.*\);(?!.*RDI_BEGIN\s*\()|(?!.*RDI_END\s*\())""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin_end - All RDI measurement specifications must be enclosed between RDI_BEGIN() and RDI_END() calls. |", 0.96)
    except:
        sm = """rdi\..*\(.*\);(?!.*RDI_BEGIN\s*\()|(?!.*RDI_END\s*\())""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin_end - All RDI measurement specifications must be enclosed between RDI_BEGIN() and RDI_END() calls. |", 0.96)
    return None

# Hash: 5090b55e90a325f0
@register_rule("rdi_begin_end_required")
def _chk_rdi_begin_end_required(lines, code, sample):
    """All RDI measurement and configuration calls must be placed between RDI_BEGIN() and RDI_END() to ensure proper instrumentation."""
    import re
    try:
        pat = re.compile(r"""rdi\.[a-zA-Z0-9_]+\s*\([^)]*\)\s*\.[a-zA-Z0-9_]+\s*\([^)]*\)(?!.*RDI_BEGIN)""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin - All RDI measurement and configuration calls must be placed between RDI_BEGIN() and RDI_END() to ensure proper instrumentation. |", 0.96)
    except:
        sm = """rdi\.[a-zA-Z0-9_]+\s*\([^)]*\)\s*\.[a-zA-Z0-9_]+\s*\([^)]*\)(?!.*RDI_BEGIN)""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin - All RDI measurement and configuration calls must be placed between RDI_BEGIN() and RDI_END() to ensure proper instrumentation. |", 0.96)
    return None

# Hash: 81cbdc7733347223
@register_rule("rdi_end_missing")
def _chk_rdi_end_missing(lines, code, sample):
    """Every RDI_BEGIN() call must be paired with a corresponding RDI_END() before exiting the scope or function."""
    import re
    try:
        pat = re.compile(r"""RDI_BEGIN\s*\(\)\s*;(?:(?!RDI_END\s*\(\)).)*$""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_rdi_end - Every RDI_BEGIN() call must be paired with a corresponding RDI_END() before exiting the scope or function. |", 0.96)
    except:
        sm = """RDI_BEGIN\s*\(\)\s*;(?:(?!RDI_END\s*\(\)).)*$""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_rdi_end - Every RDI_BEGIN() call must be paired with a corresponding RDI_END() before exiting the scope or function. |", 0.96)
    return None

# Hash: fd5edac59ff364db
@register_rule("rdi_begin_end_required")
def _chk_rdi_begin_end_required(lines, code, sample):
    """All RDI measurement sequences must be enclosed within RDI_BEGIN() and RDI_END() macros to ensure proper initialization and finalization."""
    import re
    try:
        pat = re.compile(r"""rdi\..*\.execute\s*\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin_end - All RDI measurement sequences must be enclosed within RDI_BEGIN() and RDI_END() macros to ensure proper initialization and finalization. |", 0.96)
    except:
        sm = """rdi\..*\.execute\s*\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: missing_rdi_begin_end - All RDI measurement sequences must be enclosed within RDI_BEGIN() and RDI_END() macros to ensure proper initialization and finalization. |", 0.96)
    return None

# Hash: f62a6eb55344235f
@register_rule("no_multiple_burst_calls")
def _chk_no_multiple_burst_calls(lines, code, sample):
    """When using func().burst(label) for multi‑port bursts, do not invoke another burst() on the same chain."""
    import re
    try:
        pat = re.compile(r"""func\(\).*\.burst\([^\)]*\)\.burst\(""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: multiple_burst_calls - When using func().burst(label) for multi‑port bursts, do not invoke another burst() on the same chain. |", 0.97)
    except:
        sm = """func\(\).*\.burst\([^\)]*\)\.burst\(""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: multiple_burst_calls - When using func().burst(label) for multi‑port bursts, do not invoke another burst() on the same chain. |", 0.97)
    return None

# Hash: 79c4bcdb32381d5b
@register_rule("invalid_rdi_method_chain")
def _chk_invalid_rdi_method_chain(lines, code, sample):
    """Detects usage of undefined or incomplete RDI API methods in a fluent call chain."""
    import re
    try:
        pat = re.compile(r"""rdi\.[a-zA-Z]+\([^\)]*\)(?:\.[a-zA-Z_][a-zA-Z0-9_]*)(?!\s*\()""", re.IGNORECASE)
        for L in lines:
            if pat.search(L.stripped):
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - Detects usage of undefined or incomplete RDI API methods in a fluent call chain. |", 0.96)
    except:
        sm = """rdi\.[a-zA-Z]+\([^\)]*\)(?:\.[a-zA-Z_][a-zA-Z0-9_]*)(?!\s*\()""".lower()
        for L in lines:
            if sm in L.stripped.lower():
                return (L.line_number, f"Line {L.line_number}: invalid_method_call - Detects usage of undefined or incomplete RDI API methods in a fluent call chain. |", 0.96)
    return None
